export const LAUNCH_DAY = "2026-08-29T00:00:00.000Z";

export type DailyList = {
  theme: string;
  words: string[];
};

export function getTodayInfo(now = Date.now()): {
  dayId: string;
  theme: string;
  words: string[];
} {
  const launch = Date.parse(LAUNCH_DAY);
  const dayIndex = Math.floor((now - launch) / 86_400_000);
  const list = dailyLists[(((dayIndex % 100) + 100) % 100) as number] as DailyList;
  const dayId = new Date(now).toISOString().slice(0, 10);
  return { dayId, theme: list.theme, words: list.words.slice() };
}

export const dailyLists = [
  {"theme":"Sandwich","words":["Cheese","Tomato","Mayo","Bread","Mustard","Lettuce","Tuna","Ham","Turkey","Ketchup","Onion","Pickles","Salt","Pepper","Bacon"]},
  {"theme":"Ocean","words":["Wave","Tide","Coral","Kelp","Shark","Whale","Current","Foam","Reef","Shell","Otter","Dolphin","Spray","Cove","Anemone"]},
  {"theme":"Forest","words":["Moss","Fern","Trail","Oak","Pine","Deer","Owl","Canopy","Creek","Acorn","Fox","Glade","Root","Bark","Thicket"]},
  {"theme":"Kitchen","words":["Pan","Knife","Oven","Bowl","Whisk","Spoon","Ladle","Grater","Pot","Kettle","Board","Tongs","Colander","Peeler","Spatula"]},
  {"theme":"Soccer","words":["Goal","Ball","Cleat","Pitch","Whistle","Jersey","Corner","Striker","Keeper","Midfield","Penalty","Tackle","Header","Net","Referee"]},
  {"theme":"Piano","words":["Key","Pedal","Chord","Scale","Sonata","Hammer","String","Lid","Bench","Octave","Etude","Piano","Damper","Action","Recital"]},
  {"theme":"Dogs","words":["Leash","Collar","Paw","Bark","Fetch","Puppy","Muzzle","Kennel","Treat","Tail","Howl","Terrier","Beagle","Hound","Retriever"]},
  {"theme":"Storm","words":["Rain","Cloud","Storm","Puddle","Umbrella","Thunder","Drizzle","Flood","Mist","Lightning","Downpour","Drop","Shower","Gale","Rainbow"]},
  {"theme":"Garden","words":["Soil","Seed","Hose","Spade","Tulip","Weed","Compost","Trellis","Mulch","Bed","Trowel","Bloom","Row","Harvest","Plot"]},
  {"theme":"Candy","words":["Gummy","Lollipop","Caramel","Taffy","Fudge","Nougat","Licorice","Toffee","Jellybean","Chocolate","Mint","Truffle","Sour","Chew","Brittle"]},
  {"theme":"Cars","words":["Engine","Wheel","Brake","Axle","Hood","Trunk","Bumper","Dashboard","Tire","Gear","Clutch","Mirror","Headlight","Seatbelt","Chassis"]},
  {"theme":"Clothes","words":["Shirt","Pants","Coat","Dress","Sock","Scarf","Belt","Jacket","Sweater","Skirt","Tie","Vest","Hoodie","Blouse","Shorts"]},
  {"theme":"Fruit","words":["Apple","Pear","Mango","Peach","Grape","Plum","Cherry","Lemon","Orange","Banana","Kiwi","Melon","Papaya","Guava","Fig"]},
  {"theme":"Bakery","words":["Cake","Frosting","Layer","Icing","Sponge","Candle","Batter","Slice","Fondant","Cupcake","Tier","Glaze","Crumbs","Pan","Whisk"]},
  {"theme":"Beach","words":["Sand","Towel","Surf","Shell","Dune","Tide","Cast","Umbrella","Boardwalk","Palm","Pebble","Suntan","Wave","Bucket","Pier"]},
  {"theme":"Birds","words":["Robin","Sparrow","Eagle","Hawk","Wren","Finch","Owl","Heron","Crow","Dove","Falcon","Crane","Jay","Swallow","Stork"]},
  {"theme":"Flowers","words":["Rose","Lily","Daisy","Tulip","Orchid","Iris","Peony","Poppy","Violet","Dahlia","Lotus","Aster","Lilac","Pansy","Zinnia"]},
  {"theme":"Fish","words":["Trout","Salmon","Bass","Cod","Tuna","Pike","Perch","Carp","Eel","Haddock","Mackerel","Catfish","Snapper","Grouper","Herring"]},
  {"theme":"Space","words":["Mars","Venus","Saturn","Jupiter","Mercury","Neptune","Comet","Orbit","Crater","Moon","Asteroid","Galaxy","Nebula","Star","Eclipse"]},
  {"theme":"Camping","words":["Tent","Fire","Lantern","Trail","Backpack","Compass","Canteen","Hammock","Stakes","Kindling","Cot","Flashlight","Binoculars","Campfire","Pack"]},
  {"theme":"Breakfast","words":["Eggs","Toast","Bacon","Pancake","Waffle","Oatmeal","Cereal","Yogurt","Bagel","Syrup","Omelet","Hash","Muffin","Jam","Coffee"]},
  {"theme":"Pizza","words":["Dough","Sauce","Pepperoni","Mozzarella","Crust","Olive","Basil","Slice","Oven","Peel","Oregano","Garlic","Mushroom","Sausage","Anchovy"]},
  {"theme":"Coffee","words":["Espresso","Latte","Foam","Bean","Roast","Mug","Grinder","Steam","Crema","Shot","Cappuccino","Filter","Drip","Barista","Brew"]},
  {"theme":"Winter","words":["Snow","Flake","Sled","Icicle","Blizzard","Frost","Parka","Mittens","Scarf","Shovel","Igloo","Thaw","Sleet","Drift","Powder"]},
  {"theme":"Summer","words":["Sun","Heat","Picnic","Lemonade","Shorts","Fan","Popsicle","Sandals","Grill","Hammock","Drought","Shade","Humidity","Noon","Patio"]},
  {"theme":"Cats","words":["Whisker","Purr","Kitten","Litter","Yarn","Claw","Nap","Tabby","Meow","Feline","Pounce","Lap","Scratch","Calico","Siamese"]},
  {"theme":"Horses","words":["Saddle","Hoof","Mane","Stable","Reins","Gallop","Trot","Bridle","Horseshoe","Pasture","Foal","Hay","Stall","Jockey","Canter"]},
  {"theme":"Farm","words":["Cow","Pig","Sheep","Goat","Chicken","Tractor","Barn","Silo","Hay","Fence","Rooster","Lamb","Calf","Trough","Pasture"]},
  {"theme":"Safari","words":["Lion","Tiger","Zebra","Giraffe","Elephant","Panda","Monkey","Hippo","Rhino","Lemur","Cheetah","Camel","Koala","Otter","Jaguar"]},
  {"theme":"Bugs","words":["Ant","Bee","Beetle","Moth","Cricket","Wasp","Dragonfly","Firefly","Termite","Aphid","Ladybug","Hornet","Cicada","Gnat","Locust"]},
  {"theme":"Trees","words":["Maple","Birch","Cedar","Willow","Elm","Spruce","Ash","Poplar","Redwood","Cypress","Hickory","Beech","Alder","Fir","Hemlock"]},
  {"theme":"Vegetables","words":["Carrot","Broccoli","Spinach","Celery","Potato","Cabbage","Zucchini","Beet","Radish","Kale","Leek","Turnip","Squash","Peas","Corn"]},
  {"theme":"Spices","words":["Cinnamon","Cumin","Paprika","Nutmeg","Clove","Ginger","Turmeric","Oregano","Thyme","Basil","Sage","Cardamom","Coriander","Pepper","Saffron"]},
  {"theme":"Cheese","words":["Cheddar","Brie","Gouda","Swiss","Feta","Mozzarella","Parmesan","Provolone","Ricotta","Havarti","Manchego","Gruyere","Colby","Asiago","Camembert"]},
  {"theme":"Bread","words":["Baguette","Sourdough","Rye","Brioche","Ciabatta","Pita","Roll","Loaf","Crust","Yeast","Flour","Boule","Focaccia","Pretzel","Naan"]},
  {"theme":"Pasta","words":["Spaghetti","Penne","Fettuccine","Lasagna","Ravioli","Linguine","Macaroni","Gnocchi","Orzo","Rigatoni","Farfalle","Tortellini","Noodle","Sauce","Basil"]},
  {"theme":"Sushi","words":["Rice","Nori","Wasabi","Ginger","Tuna","Salmon","Roll","Soy","Avocado","Eel","Tempura","Roe","Chopstick","Miso","Edamame"]},
  {"theme":"Mexican","words":["Taco","Salsa","Tortilla","Guacamole","Jalapeno","Queso","Cilantro","Lime","Bean","Rice","Chip","Burrito","Nacho","Carne","Corn"]},
  {"theme":"Ice Cream","words":["Cone","Scoop","Vanilla","Chocolate","Strawberry","Sundae","Sprinkle","Waffle","Pint","Cherry","Fudge","Banana","Milkshake","Swirl","Bowl"]},
  {"theme":"Tea","words":["Kettle","Leaves","Steep","Mug","Jasmine","Matcha","Pot","Infuser","Honey","Lemon","Chai","Oolong","Cup","Saute","Strainer"]},
  {"theme":"Baseball","words":["Bat","Glove","Inning","Pitcher","Catcher","Home","Diamond","Dugout","Umpire","Fastball","Shortstop","Outfield","Helmet","Cleat","Base"]},
  {"theme":"Basketball","words":["Hoop","Court","Dribble","Dunk","Layup","Rebound","Foul","Three","Bench","Jersey","Backboard","Net","Coach","Timeout","Assist"]},
  {"theme":"Tennis","words":["Racket","Serve","Ace","Net","Court","Deuce","Lob","Volley","Clay","Grip","Baseline","Smash","Set","Match","Umpire"]},
  {"theme":"Swimming","words":["Lane","Stroke","Goggles","Kick","Lap","Block","Flip","Buoy","Cap","Dive","Relay","Wall","Splash","Breath","Turn"]},
  {"theme":"Cycling","words":["Pedal","Chain","Helmet","Spoke","Saddle","Brake","Derailleur","Handlebar","Tire","Bell","Pump","Frame","Cog","Jersey","Trail"]},
  {"theme":"Skiing","words":["Ski","Slope","Lift","Pole","Boot","Goggle","Powder","Run","Lodge","Bind","Mogul","Alpine","Wax","Glove","Chairlift"]},
  {"theme":"Running","words":["Mile","Pace","Shoe","Track","Sprint","Lunge","Stride","Bib","Stopwatch","Hydration","Hill","Lap","Block","Relay","Finish"]},
  {"theme":"Guitar","words":["Fret","Pick","Amp","Chord","String","Neck","Bridge","Tuner","Cable","Pedal","Riff","Capo","Jack","Knob","Solo"]},
  {"theme":"Drums","words":["Snare","Kick","Cymbal","Hihat","Tom","Stick","Pedal","Throne","Rim","Brush","Fill","Groove","Hardware","Bag","Beat"]},
  {"theme":"Orchestra","words":["Violin","Cello","Flute","Oboe","Harp","Viola","Clarinet","Trumpet","Trombone","Tuba","Bassoon","Piccolo","Horn","Baton","Score"]},
  {"theme":"Painting","words":["Canvas","Brush","Easel","Palette","Oil","Acrylic","Studio","Gesso","Varnish","Sketch","Portrait","Mural","Pigment","Linseed","Frame"]},
  {"theme":"Photography","words":["Lens","Shutter","Tripod","Aperture","Flash","Darkroom","Zoom","Filter","Sensor","Focus","Exposure","Crop","Print","Album","Prism"]},
  {"theme":"Sculpture","words":["Clay","Chisel","Marble","Bronze","Mold","Kiln","Armature","Pedestal","Bust","Relief","Plaster","Wax","Forge","Anvil","Studio"]},
  {"theme":"Movies","words":["Reel","Scene","Ticket","Popcorn","Trailer","Credits","Screen","Usher","Premiere","Director","Stunt","Score","Closeup","Cut","Set"]},
  {"theme":"Theater","words":["Stage","Curtain","Script","Role","Props","Monologue","Spotlight","Wings","Encore","Cast","Makeup","Intermission","Pit","Booth","Cue"]},
  {"theme":"Books","words":["Novel","Spine","Chapter","Library","Bookmark","Author","Page","Hardcover","Paperback","Index","Preface","Shelf","Folio","Blurb","Plot"]},
  {"theme":"School","words":["Desk","Chalk","Locker","Bell","Homework","Pencil","Ruler","Globe","Backpack","Quiz","Recess","Hallway","Teacher","Notebook","Eraser"]},
  {"theme":"Hospital","words":["Nurse","Gown","Stethoscope","Ward","Syringe","Gauze","Chart","Bed","Mask","Iodine","Crutch","Cast","Clinic","Gurney","Bandage"]},
  {"theme":"Firehouse","words":["Hose","Hydrant","Helmet","Engine","Ladder","Axe","Siren","Boot","Nozzle","Smoke","Alarm","Dalmatian","Coat","Rescue","Station"]},
  {"theme":"Airport","words":["Runway","Gate","Cockpit","Luggage","Hangar","Jet","Taxi","Tower","Passport","Seat","Tray","Wing","Fuselage","Pilot","Tarmac"]},
  {"theme":"Trains","words":["Track","Caboose","Conductor","Platform","Ticket","Engine","Sleeper","Freight","Whistle","Switch","Depot","Rail","Coach","Signal","Tunnel"]},
  {"theme":"Boats","words":["Hull","Mast","Sail","Anchor","Deck","Keel","Rudder","Bow","Stern","Oar","Buoy","Port","Hatch","Winch","Rigging"]},
  {"theme":"Tools","words":["Hammer","Nail","Saw","Drill","Screw","Wrench","Level","Pliers","Chisel","Clamp","Tape","Bit","Vice","Rasp","Mallet"]},
  {"theme":"Office","words":["Stapler","Folder","Clip","Toner","Binder","Inbox","Memo","Paperclip","Shredder","Whiteboard","Marker","Label","Tray","Stamp","Envelope"]},
  {"theme":"Bedroom","words":["Pillow","Duvet","Nightstand","Lamp","Alarm","Sheet","Blanket","Mattress","Drawer","Hamper","Robe","Slippers","Shade","Quilt","Headboard"]},
  {"theme":"Bathroom","words":["Towel","Soap","Shower","Sink","Mirror","Toothbrush","Comb","Lotion","Bathmat","Razor","Shampoo","Drain","Tap","Robe","Tile"]},
  {"theme":"Living Room","words":["Couch","Rug","Remote","Lamp","Ottoman","Cushion","Throw","Shelf","Vase","Clock","Frame","Blanket","Table","Speaker","Plant"]},
  {"theme":"Gems","words":["Ruby","Emerald","Sapphire","Diamond","Opal","Pearl","Topaz","Garnet","Jade","Amber","Onyx","Quartz","Amethyst","Jewel","Bezel"]},
  {"theme":"Metals","words":["Iron","Copper","Gold","Silver","Steel","Bronze","Tin","Zinc","Nickel","Lead","Chrome","Brass","Platinum","Alloy","Ore"]},
  {"theme":"Mountains","words":["Peak","Ridge","Cliff","Summit","Valley","Pass","Glacier","Basecamp","Switchback","Cairn","Alpenglow","Scree","Col","Arete","Hut"]},
  {"theme":"Desert","words":["Dune","Cactus","Oasis","Sand","Heat","Mirage","Lizard","Camel","Arroyo","Mesa","Dry","Sun","Rock","Shade","Wind"]},
  {"theme":"Jungle","words":["Vine","Canopy","Parrot","Jaguar","Rain","Liana","Orchid","Mist","Howler","Fern","River","Mud","Trail","Hut","Drum"]},
  {"theme":"Rivers","words":["Current","Bank","Delta","Eddy","Ford","Rapid","Bend","Mouth","Source","Ferry","Canoe","Ripple","Silt","Weir","Lock"]},
  {"theme":"Lakes","words":["Shore","Dock","Canoe","Lure","Reed","Lily","Pier","Rowboat","Bass","Ice","Cabin","Paddle","Inlet","Cove","Fish"]},
  {"theme":"Volcanoes","words":["Crater","Lava","Ash","Magma","Vent","Slope","Rumble","Plume","Caldera","Basalt","Fumarole","Cone","Eruption","Flow","Rift"]},
  {"theme":"Dinosaurs","words":["TRex","Triceratops","Stegosaur","Raptor","Fossil","Skull","Claw","Nest","Egg","Museum","Bone","Herbivore","Jurassic","Track","Jaw"]},
  {"theme":"Fantasy","words":["Castle","Knight","Sword","Shield","Quest","Wizard","Dungeon","Spell","Crown","Scroll","Potion","Griffin","Keep","Moat","Dragon"]},
  {"theme":"Medieval","words":["Armor","Lance","Herald","Keep","Drawbridge","Portcullis","Squire","Chalice","Tapestry","Throne","Catapult","Moat","Turret","Chainmail","Gauntlet"]},
  {"theme":"Pirates","words":["Parrot","Map","Chest","Cutlass","Grog","Mast","Jolly","Doubloon","Pegleg","Patch","Island","Cannon","Plank","Rum","Hook"]},
  {"theme":"Circus","words":["Tent","Clown","Ring","Trapeze","Elephant","Unicycle","Sawdust","Ticket","Cannon","Lion","Juggler","Tightrope","Popcorn","Wagon","Calliope"]},
  {"theme":"Carnival","words":["Ferris","Cotton","Ticket","Booth","Carousel","Prize","Midway","Balloon","Whack","Skee","Corn","Lemonade","Lights","Crowd","Ride"]},
  {"theme":"Halloween","words":["Pumpkin","Costume","Candy","Ghost","Witch","Bat","Cobweb","Cauldron","Mask","Broom","Skull","Lantern","Trick","Treat","Moon"]},
  {"theme":"Christmas","words":["Tree","Ornament","Tinsel","Stocking","Wreath","Carol","Sleigh","Gift","Star","Eggnog","Mistletoe","Candle","Snowman","Ribbon","Nativity"]},
  {"theme":"Birthday","words":["Cake","Balloon","Present","Candle","Party","Hat","Wish","Card","Pinata","Streamers","Guest","Song","Slice","Clown","Banner"]},
  {"theme":"Wedding","words":["Ring","Veil","Toast","Bouquet","Altar","Gown","Tux","Vows","Cake","Dance","Aisle","Confetti","Band","Kiss","Rice"]},
  {"theme":"Baby","words":["Crib","Bottle","Diaper","Rattle","Stroller","Bib","Pacifier","Onesie","Mobile","Blanket","Lullaby","Bassinet","Wipe","Teether","Socks"]},
  {"theme":"Body","words":["Hand","Foot","Elbow","Knee","Wrist","Ankle","Shoulder","Spine","Skull","Rib","Thumb","Palm","Shin","Hip","Jaw"]},
  {"theme":"Jobs","words":["Baker","Pilot","Nurse","Chef","Farmer","Miner","Welder","Judge","Barber","Mason","Tailor","Sailor","Painter","Clerk","Guard"]},
  {"theme":"Computers","words":["Mouse","Keyboard","Monitor","Cable","Chip","Drive","Router","Port","Fan","Case","Screen","Cursor","File","Folder","Pixel"]},
  {"theme":"Phones","words":["Screen","Case","Charger","App","Camera","Speaker","Button","Bezel","Notch","Swipe","Icon","Battery","Lens","Stand","Haptic"]},
  {"theme":"Shoes","words":["Sneaker","Boot","Sandal","Heel","Loafer","Cleat","Slipper","Oxford","Mule","Wedge","Insole","Laces","Tongue","Sole","Pump"]},
  {"theme":"Hats","words":["Cap","Beanie","Beret","Fedora","Visor","Crown","Brim","Turban","Bonnet","Toque","Cloche","Trilby","Boater","Derby","Tiara"]},
  {"theme":"Table","words":["Fork","Plate","Napkin","Glass","Bowl","Cup","Saucer","Pitcher","Trivet","Coaster","Placemat","Tureen","Carafe","Ladle","Cruet"]},
  {"theme":"Sewing","words":["Needle","Thread","Thimble","Bobbin","Seam","Hem","Pattern","Pin","Scissors","Zipper","Button","Dart","Pleat","Bias","Spool"]},
  {"theme":"Building","words":["Brick","Mortar","Beam","Joist","Rafter","Stud","Siding","Shingle","Gutter","Foundation","Lintel","Sill","Plumb","Square","Level"]},
  {"theme":"Bees","words":["Hive","Honey","Comb","Pollen","Queen","Worker","Nectar","Swarm","Stinger","Wax","Brood","Frame","Smoker","Veil","Apiary"]},
  {"theme":"Knitting","words":["Yarn","Knit","Purl","Skein","Needle","Stitch","Row","Gauge","Cast","Bind","Swatch","Cable","Rib","Bobble","Hook"]},
  {"theme":"Writing","words":["Ink","Quill","Parchment","Seal","Ledger","Scroll","Folio","Blotter","Nib","Wax","Stamp","Cipher","Margin","Codex","Vellum"]},
  {"theme":"Chess","words":["Pawn","Rook","Knight","Bishop","Queen","King","Check","Gambit","Castle","Rank","File","Mate","Opening","Endgame","Tempo"]},
  {"theme":"Cards","words":["Ace","King","Queen","Jack","Joker","Suit","Deal","Hand","Bluff","Fold","River","Flop","Chip","Ante","Deck"]}
];
